spring:
      datasource:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.1.201:3306/test
          username: operator
          password: operator
      redis:
          password: 
          pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0
          timeout: 0
          commandTimeout: 5000
          cluster:
            nodes: 192.168.1.201:7001,192.168.1.201:7002,192.168.1.201:7003,192.168.1.201:7004,192.168.1.201:7005,192.168.1.201:7006


influxdb:
     url: 'http://192.168.1.201:8086'
     user: influx
     password: influx
     


